name: main
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Docker build, tag, and push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker build, tag, and push
      uses: pangzineng/Github-Action-One-Click-Docker@master
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
